### ISSUE TITLE
Expenses Page

### ISSUE THREAD

**Issue by queply-innovations** [queply-innovations/RoyalGlassSupply-app#21]
### BUG 

**adding expenses**

> "Request failed with status code 500"
https://snipboard.io/0j34wz.jpg
"SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tufyqpmy_staging`.`operation_expenses`, CONSTRAINT `operation_expenses_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE) (Connection: mysql, SQL: insert into `operation_expenses` (`title`, `date_of_operation`, `amount`, `notes`, `updated_at`, `created_at`) values (Test, 2024-04-09, 1234, 5000, 2024-04-09 14:32:20, 2024-04-09 14:32:20))"

**Expenses Table**
https://snipboard.io/sX5Hha.jpg

**Comment by eybrithingweird** [comment]
Cause of bug should be good by now. Probable cause of issue: 

1. User account data may not have been properly added last time (bug also apparent in some user accounts with not data in user_roles)
2. Auth wasn't loaded correctly at the time

Will check when it's fine to add data to the db (can't rn because of simulation)
